wip

diff --git a/run-reframe b/run-reframe
--- a/run-reframe
+++ b/run-reframe
@@ -10,13 +10,15 @@ red ()    { echo "\e[1;31m$1\e[m"; }
 yellow () { echo "\e[1;33m$1\e[m"; }
 log () { printf "$(yellow "[log $(datetime)]") $1\n"; }
 err () { printf "$(red "[error $(datetime)]") $1\n"; exit 1; }
+exit_without_error () {log "$1"; exit 0;}
 
 usage () {
     echo "usage: reframe-run -n name -s system"
     echo ""
     echo "where:"
     echo "  name:        the name of the stack"
-    echo "  system:      the cluster name \(e.g. of balfrin, hohgant, clariden\)"
+    echo "  uarch:       microarchitecture \(one of a100, zen2, zen3, mi200\)"
+    echo "  system:      the cluster name \(e.g. of balfrin, clariden, eiger\)"
     echo ""
     [[ "" == "$1" ]] && exit 0
     err "$1"
@@ -24,6 +26,7 @@ usage () {
 
 system="-"
 name="-"
+uarch="-"
 ci_path="$CI_PROJECT_DIR"
 test_path="$ci_path/$CI_JOB_ID"
 
@@ -32,11 +35,13 @@ do
     case "${flag}" in
         n) name=${OPTARG};;
         s) system=${OPTARG};;
+        u) uarch=${OPTARG};;
     esac
 done
 
 [[ "-" == "${system}"      ]] && usage "missing system argument"
 [[ "-" == "${name}"        ]] && usage "missing name argument"
+[[ "-" == "${uarch}"       ]] && usage "missing uarch argument"
 
 build_id=${CI_PIPELINE_ID}
 
@@ -44,6 +49,7 @@ log "SCRATCH     ${SCRATCH}"
 log "USER        ${USER}"
 log "name        ${name}"
 log "system      ${system}"
+log "uarch       ${uarch}"
 log "build_id    ${build_id}"
 log "ci_path     ${ci_path}"
 log "test_path   ${test_path}"
@@ -58,16 +64,19 @@ artifact_path="${test_path}/artifacts"
 mkdir -p $artifact_path
 
 rego=jfrog.svc.cscs.ch/uenv
-repo_base=build/${CLUSTER_NAME}/${build_id}/${name}
-repo=${repo_base}:latest
+#repo_base=build/${system}/${uarch}/${name}/${build_id}
+#repo=${repo_base}:latest
+repo_base=build/${system}/${uarch}/${name}
+repo=${repo_base}:${build_id}
 
 #
 # Download the meta data from jfrog
 #
 
 # step 1: look up the digest of the meta data
+log "looking for meta data for image at $rego/$repo"
 meta_digest=$(oras discover --registry-config ${jfrog_creds_path} --output json --artifact-type 'uenv/meta' $rego/$repo | jq -r '.manifests[0].digest')
-log "metadata digest $meta_digest"
+log "found metadata digest $meta_digest"
 
 # step 2: download the meta data
 log "downloading meta data image from ${rego}/${repo_base}@$meta_digest"
@@ -80,11 +89,7 @@ log "Using artifacts in $artifact_path"
 find "${artifact_path}"
 
 log "looking for reframe metadata in ${rfm_meta_path}"
-if [[ ! -f "${rfm_meta_path}" ]]
-then
-    log "no reframe meta data provided: skipping tests"
-    exit 0
-fi
+[[ -f "${rfm_meta_path}" ]] || exit_without_error "no reframe meta data provided: skipping tests"
 
 # copy the meta data to the location where reframe expects to find it.
 cp $rfm_meta_path "${artifact_path}/store.yaml"
@@ -126,7 +131,7 @@ then
     cat $report_path
     oras attach --registry-config ${jfrog_creds_path} --artifact-type uenv/reframe "${rego}/${repo}" "${report_path}"
 else
-    log "Reframe test run failed - exiting without pushing a report artifact"
+    err "Reframe test run failed - no report artifact pushed"
 fi
 
 deactivate
