draft logging in to jfrog with oras and push image to uenv registry

diff --git a/stack-build b/stack-build
--- a/stack-build
+++ b/stack-build
@@ -1,13 +1,9 @@
 #!/bin/bash
 
-#usage: stack-build -r recipe -s system -n name -b build-root
-
 datetime () { date +"%Y-%m-%d %H:%M:%S"; }
 
 [[ -t 1 ]] && interm=yes
 
-#red ()    { [[ "${interm}" = "yes" ]] && echo "\e[1;31m$1\e[m" || echo "$1"; }
-#yellow () { [[ "${interm}" = "yes" ]] && echo "\e[1;33m$1\e[m" || echo "$1"; }
 red ()    { echo "\e[1;31m$1\e[m"; }
 yellow () { echo "\e[1;33m$1\e[m"; }
 log () { printf "$(yellow "[log $(datetime)]") $1\n"; }
@@ -63,7 +59,7 @@ log "system      ${system}"
 log "recipe-path ${recipe_path}"
 log "build-id    ${build_id}"
 log "build-root  ${build_root}"
-log "build-path  ${build_path}" 
+log "build-path  ${build_path}"
 [[ ! -z ${spack_develop} ]] && log "develop"
 
 # Check if the recipe path exists
@@ -136,7 +132,26 @@ fi
 
 # Obtain credentials for JFrog - required to push the image and meta-data
 creds_json=$(curl --retry 5 --retry-connrefused --fail --silent "$CSCS_CI_MW_URL/credentials?token=$CI_JOB_TOKEN&creds=container_registry")
-creds_short=$(echo ${creds_json} | jq --join-output '.container_registry.username + ":" + .container_registry.password')
+oras_creds=$(echo ${creds_json} | jq --join-output '"--username " + .container_registry.username + " --password " +.container_registry.password')
+#creds_short=$(echo ${creds_json} | jq --join-output '.container_registry.username + ":" + .container_registry.password')
+
+echo ==== JSON credentials
+echo ${creds_json}
+
+echo ==== ORAS credentials
+echo ${oras_creds}
+
+oras_u=$(echo ${creds_json} | jq '.container_registry.username')
+oras_p=$(echo ${creds_json} | jq '.container_registry.password')
+
+echo ==== ORAS credentials
+
+echo username: ${oras_u}
+echo password: ${oras_p}
+
+oras login jfrog.svc.cscs.ch --username "${oras_u}" --password "${oras_p}"
+
+rego="https://jfrog.svc.cscs.ch/artifactory/uenv"
 artifactory_url="https://jfrog.svc.cscs.ch/artifactory"
 repo_path="alps-uenv/build/${build_id}/${system}/${name}"
 
@@ -150,29 +165,40 @@ source_path="${build_path}/store.squashfs"
 # `curl -v` will print on stderr all headers received back, i.e. also something like the string "< HTTP/2 200",
 # which we match. However it is on stderr, while output is on stdout, therefore we exchange the two and grep then
 # for the status code, which fails if 2XX cannot be found
-curl_opts="-v --retry 10 --retry-connrefused --silent"
-log "pushing image '${source_path}' to '${destination_path}'"
+#curl_opts="-v --retry 10 --retry-connrefused --silent"
+#log "pushing image '${source_path}' to '${destination_path}'"
 # note: use retry, because pushing to JFrog was not 100% reliable during development of this script.
-curl ${curl_opts} -u "${creds_short}" -X PUT "${destination_path}" -T "${source_path}" 3>&1 1>&2 2>&3 | egrep -q '^< HTTP.*2[0-9]{2}[[:space:]]*$'
+#curl ${curl_opts} -u "${creds_short}" -X PUT "${destination_path}" -T "${source_path}" 3>&1 1>&2 2>&3 | egrep -q '^< HTTP.*2[0-9]{2}[[:space:]]*$'
+
+echo oras login jfrog.svc.cscs.ch --username "${oras_u}" --password "${oras_p}"
+oras login jfrog.svc.cscs.ch --username "${oras_u}" --password "${oras_p}"
+[[ $? -eq 0  ]] || err "failed logging into oras - can't push image to uenv registry"
+
+log "build-path  ${build_path}"
+
+rego=jfrog.svc.cscs.ch/uenv
+repo=build/${CLUSTER_NAME}/${build_id}/${name}:build
+
+oras push ${rego}/${repo} --artifact-type application/vnd.cscs.uenv.config store.sqfs
 [[ $? -eq 0  ]] || err "failed to push image"
 
 # push the metadata to jfrog
-destination_path="${artifactory_url}/${repo_path}"
-log "pushing meta data '${source_path}' to '${destination_path}'"
-for source in $(cd store; find meta -type f)
-do
-    log "pushing ${destination_path}/${source}"
-    curl ${curl_opts} -u "${creds_short}" -X PUT "${destination_path}/${source}" -T "store/${source}" 3>&1 1>&2 2>&3 | egrep -q '^< HTTP.*2[0-9]{2}[[:space:]]*$'
-    if [ ! $? -eq 0 ]; then
-        err "unable to push meta data file store/$source"
-    fi
-done
+#destination_path="${artifactory_url}/${repo_path}"
+#log "pushing meta data '${source_path}' to '${destination_path}'"
+#for source in $(cd store; find meta -type f)
+#do
+#    log "pushing ${destination_path}/${source}"
+#    curl ${curl_opts} -u "${creds_short}" -X PUT "${destination_path}/${source}" -T "store/${source}" 3>&1 1>&2 2>&3 | egrep -q '^< HTTP.*2[0-9]{2}[[:space:]]*$'
+#    if [ ! $? -eq 0 ]; then
+#        err "unable to push meta data file store/$source"
+#    fi
+#done
 
-artifact_path="$CI_PROJECT_DIR/artifacts"
-log "copying meta-data to ${artifact_path}"
-mkdir "${artifact_path}"
-cp -r store/meta "${artifact_path}"
+#artifact_path="$CI_PROJECT_DIR/artifacts"
+#log "copying meta-data to ${artifact_path}"
+#mkdir "${artifact_path}"
+#cp -r store/meta "${artifact_path}"
 
-log "clean up build path '${build_path}'"
-(rm -rf ${build_path})
+#log "clean up build path '${build_path}'"
+#(rm -rf ${build_path})
 
