wip

diff --git a/stack-build b/stack-build
--- a/stack-build
+++ b/stack-build
@@ -116,10 +116,35 @@ fi
 rm -rf "$tool_path" "$cluster_path"
 
 ##
+# Download oras in the build path
+##
+
+# Obtain credentials for JFrog - required to push the image and meta-data
+creds_json=$(curl --retry 5 --retry-connrefused --fail --silent "$CSCS_CI_MW_URL/credentials?token=$CI_JOB_TOKEN&creds=container_registry")
+oras_creds=$(echo ${creds_json} | jq --join-output '"--username " + .container_registry.username + " --password " +.container_registry.password')
+
+oras_u=$(echo ${creds_json} | jq '.container_registry.username')
+oras_p=$(echo ${creds_json} | jq '.container_registry.password')
+
+echo username: ${oras_u}
+echo password: ${oras_p}
+
+log "downloading oras"
+get-oras
+oras_bin=$(realpath oras)
+[[ $? -eq 0  ]] || err "unable to download oras"
+
+log "logging in to jfrog.svc.cscs.ch with oras"
+echo oras login jfrog.svc.cscs.ch --username "${oras_u}" --password "${oras_p}"
+${oras_bin} login jfrog.svc.cscs.ch --username "${oras_u}" --password "${oras_p}"
+[[ $? -eq 0  ]] || err "failed oras login to JFrog - can't push image to uenv registry"
+
+##
 # Build the Spack stack
 ##
 
 cd "${build_path}"
+
 log "building image in ${build_path}"
 echo "env --ignore-environment PATH=/usr/bin:/bin:${PWD}/spack/bin make store.squashfs -j64"
 env --ignore-environment PATH=/usr/bin:/bin:${PWD}/spack/bin make store.squashfs -j64
@@ -134,24 +159,6 @@ fi
 # Push build artifacts to JFrog
 ##
 
-# Obtain credentials for JFrog - required to push the image and meta-data
-creds_json=$(curl --retry 5 --retry-connrefused --fail --silent "$CSCS_CI_MW_URL/credentials?token=$CI_JOB_TOKEN&creds=container_registry")
-oras_creds=$(echo ${creds_json} | jq --join-output '"--username " + .container_registry.username + " --password " +.container_registry.password')
-#creds_short=$(echo ${creds_json} | jq --join-output '.container_registry.username + ":" + .container_registry.password')
-
-echo ==== JSON credentials
-echo ${creds_json}
-
-echo ==== ORAS credentials
-echo ${oras_creds}
-
-oras_u=$(echo ${creds_json} | jq '.container_registry.username')
-oras_p=$(echo ${creds_json} | jq '.container_registry.password')
-
-echo ==== ORAS credentials
-
-echo username: ${oras_u}
-echo password: ${oras_p}
 
 rego="https://jfrog.svc.cscs.ch/artifactory/uenv"
 artifactory_url="https://jfrog.svc.cscs.ch/artifactory"
@@ -172,21 +179,11 @@ source_path="${build_path}/store.squashfs"
 # note: use retry, because pushing to JFrog was not 100% reliable during development of this script.
 #curl ${curl_opts} -u "${creds_short}" -X PUT "${destination_path}" -T "${source_path}" 3>&1 1>&2 2>&3 | egrep -q '^< HTTP.*2[0-9]{2}[[:space:]]*$'
 
-log "downloading oras"
-which get-oras
-get-oras
-[[ $? -eq 0  ]] || err "unable to download oras"
-
-log "logging in to jfrog.svc.cscs.ch with oras"
-echo oras login jfrog.svc.cscs.ch --username "${oras_u}" --password "${oras_p}"
-./oras login jfrog.svc.cscs.ch --username "${oras_u}" --password "${oras_p}"
-[[ $? -eq 0  ]] || err "failed logging into oras - can't push image to uenv registry"
-
 rego=jfrog.svc.cscs.ch/uenv
 repo=build/${CLUSTER_NAME}/${build_id}/${name}:build
 
 log "pushing store.squashfs to ${rego}/${repo}"
-oras push ${rego}/${repo} --artifact-type application/vnd.cscs.uenv.config store.squashfs
+${oras_bin} push ${rego}/${repo} --artifact-type application/vnd.cscs.uenv.config store.squashfs
 [[ $? -eq 0  ]] || err "failed to push image"
 
 # push the metadata to jfrog
