wip

diff --git a/stack-build b/stack-build
--- a/stack-build
+++ b/stack-build
@@ -49,19 +49,13 @@ done
 [[ "-" == "${recipe_path}" ]] && usage "missing recipe-path argument"
 
 build_id=$(get_build_id)
-repo_path="alps-uenv/build/${build_id}/${system}/${name}"
 build_path="/dev/shm/stack/${name}/${build_id}"
-
-log "curl \$CSCS_CI_MW_URL/credentials?token=\$CI_JOB_TOKEN&creds=jfrog"
-log "curl $CSCS_CI_MW_URL/credentials?token=$CI_JOB_TOKEN&creds=jfrog"
-log "$(curl $CSCS_CI_MW_URL/credentials?token=$CI_JOB_TOKEN&creds=jfrog)"
 
 log "name        ${name}"
 log "system      ${system}"
 log "recipe-path ${recipe_path}"
 log "build-path  ${build_path}"
 log "build-id    ${build_id}"
-log "artifactory ${repo_path}"
 
 # Check if the recipe path exists
 [[ -d "${recipe_path}" ]] || err "recipe path '$recipe_path' does not exist"
@@ -91,10 +85,25 @@ if [ ! $? -eq 0 ]; then
 fi
 
 # push to repository
-repo_image="${repo_path}/store.squashfs"
-log "pushing image to '${repo_image}'"
-jfrog rt upload --threads=16 "${build_path}/store.squashfs" "${repo_image}" > result.json
-[[ $? -eq 0 ]] || err "unable to push image to artifactory '${repo_image}'"
-failures=$(jq '.totals.failure' result.json)
-log "uploaded to jfrog with ${failures} failures"
+log          "curl --silent $CSCS_CI_MW_URL/credentials?token=$CI_JOB_TOKEN&creds=container_registry"
+creds_json="$(curl --silent $CSCS_CI_MW_URL/credentials?token=$CI_JOB_TOKEN&creds=container_registry)"
+creds_short=$(echo ${creds_json} | jq --join-output '.container_registry.username + ":" + .container_registry.password')
+
+artifactory_url="https://jfrog.svc.cscs.ch/artifactory"
+repo_path="alps-uenv/build/${build_id}/${system}/${name}"
+destination_path="${artifactory_url}/${repo_path}/store.squashfs"
+source_path="${build_path}/store.squashfs"
+log "pushing '${source_path}' to '${destination_path}'"
+
+#log "curl -u ${creds_short} -X PUT ${destination_path} -T ${source_path}"
+curl -u "${creds_short}" -X PUT "${destination_path}" -T "${source_path}"
+
+#jfrog rt upload --threads=16 "${build_path}/store.squashfs" "${repo_image}" > result.json
+#[[ $? -eq 0 ]] || err "unable to push image to artifactory '${repo_image}'"
+#failures=$(jq '.totals.failure' result.json)
+#log "uploaded to jfrog with ${failures} failures"
+
+log "image built and pushed to artifactory"
+log "clean up build path '${build_path}'"
+#rm -rf ${build_path}
 
