update stackinator version
- new stackinator version (v3 pre-release)
- update build cache configuration to follow v3
- check out cluster config from alps-cluster-config

diff --git a/scripts/setup-stackinator b/scripts/setup-stackinator
--- a/scripts/setup-stackinator
+++ b/scripts/setup-stackinator
@@ -3,27 +3,30 @@
 tool_base_path="$(pwd)"
 # check out a unique copy of stackinator for each ci task, so that
 # builds in the same pipeline do not conflict
-#tool_path="${tool_base_path}/stackinator-${build_id}"
 tool_path=`mktemp -d`
 tool_repo=https://github.com/eth-cscs/stackinator.git
-tool_version=6e269ae39618ad01fa7696fb6c859577f0d5fd1b
+tool_version=c2ad2f6e5a208c89cfe5cd84532f0a1bfde8e24a
 
-#if [ ! -d "${tool_path}" ]; then
-    log "installing stackinator from git in '${tool_path}'"
+log "installing stackinator from git in '${tool_path}'"
 
-    log "cloning git repository ${tool_repo}"
-    git clone --quiet "${tool_repo}" "${tool_path}" || err "unable to clone stackinator git repository"
+log "cloning stackinator from ${tool_repo}"
+git clone --quiet "${tool_repo}" "${tool_path}" || err "unable to clone stackinator git repository"
 
-    log "checkout stackinator ${tool_version}"
-    cd "${tool_path}"
-    git checkout --quiet "${tool_version}" || err "unable to checkout out requested version"
+log "checkout stackinator ${tool_version}"
+cd "${tool_path}"
+git checkout --quiet "${tool_version}" || err "unable to checkout out requested version"
 
-    log "bootstrap stackinator"
-    cd "${tool_path}"
-    ./bootstrap.sh || err "bootstrap failed"
+log "bootstrap stackinator"
+cd "${tool_path}"
+./bootstrap.sh || err "bootstrap failed"
 
-    cd "${tool_base_path}"
-    log "finished stackinator installation"
-#fi
+cd "${tool_base_path}"
+log "finished stackinator installation"
 
 export PATH="${tool_path}/bin:$PATH"
+
+cluster_path=`mktemp -d`
+cluster_repo=https://github.com/eth-cscs/alps-cluster-config
+
+log "cloning cluster config from ${cluster_repo}"
+git clone --quiet "${cluster_repo}" "${cluster_path}" || err "unable to clone cluster-config git repository"
diff --git a/stack-build b/stack-build
--- a/stack-build
+++ b/stack-build
@@ -66,22 +66,22 @@ log "build-path  ${build_path}"
 # Check if the recipe path exists
 [[ -d "${recipe_path}" ]] || err "recipe path '$recipe_path' does not exist"
 
-# Set up build cache mirror if a build cache exists on this system
+# Set up build cache if a build cache exists on this system
 #mirror_path=/scratch/e1000/jenkssl/uenv-cache
 mirror_path=$SCRATCH/uenv-cache
 if [ -d "${mirror_path}" ]; then
     log "found build cache at $mirror_path"
-    key_path=${mirror_path}/push-key.gpg
-    key_args="--read-only"
-    if [ -f "${key_path}" ]; then
-        key_args="--key=${key_path}"
+    echo "root: $mirror_path" > cache.yaml
+    key_path="${mirror_path}/push-key.gpg"
+    if [[ -f "${key_path}" ]]; then
+        log "found build cache key at $key_path"
+        echo "key: ${mirror_path}/push-key.gpg" >> cache.yaml
     fi
-    ./scripts/cache-configure $key_args --path="${mirror_path}" "${recipe_path}"
+    cache_flags="--cache cache.yaml"
 else
-    log "no build cache at $mirror_path - disabling"
-    ./scripts/cache-configure --disable "${recipe_path}"
+    rm -f cache.yaml
+    cache_flags=""
 fi
-#source ./scripts/generate-mirror
 
 # Initialise the stackinator
 source ./scripts/setup-stackinator
@@ -89,11 +89,11 @@ source ./scripts/setup-stackinator
 # call stackinator
 log "configuring stack"
 
-echo "stack-config -r ${recipe_path} -b ${build_path} -s ${system}"
-stack-config -r "${recipe_path}" -b "${build_path}" -s "${system}"
+echo "stack-config -r ${recipe_path} -b ${build_path} -s $cluster_path/${system} $cache_flags"
+stack-config -r "${recipe_path}" -b "${build_path}" -s "$cluster_path/${system}" $cache_flags
 
 if [ ! $? -eq 0 ]; then
-    # delete stackinator tool
+    # delete stackinator tool once it is no longer needed
     rm -rf $tool_path
     err "stack-config failed"
 fi
@@ -103,12 +103,13 @@ rm -rf $tool_path
 
 # run build
 cd "${build_path}"
-log "building image"
+log "building image in ${build_path}"
 echo "env --ignore-environment PATH=/usr/bin:/bin:${PWD}/spack/bin make store.squashfs -j64"
 env --ignore-environment PATH=/usr/bin:/bin:${PWD}/spack/bin make store.squashfs -j64
 
 if [ ! $? -eq 0 ]; then
     log "TODO: save WIP of build an store it for later inspection"
+    cp -r "${build_path}/tmp/jenkssl/spack-stage/" $CI_PROJECT_DIR
     err "error building image"
 fi
 
@@ -120,12 +121,16 @@ artifactory_url="https://jfrog.svc.cscs.ch/artifactory"
 repo_path="alps-uenv/build/${build_id}/${system}/${name}"
 destination_path="${artifactory_url}/${repo_path}/store.squashfs"
 source_path="${build_path}/store.squashfs"
-log "pushing '${source_path}' to '${destination_path}'"
 
+log "pushing image '${source_path}' to '${destination_path}'"
 curl --silent --fail -u "${creds_short}" -X PUT "${destination_path}" -T "${source_path}"
 [[ $? -eq 0  ]] || err "failed to push image"
 
-log "image built and pushed to artifactory"
+log "pushing meta data '${source_path}/meta' to '${destination_path}'"
+curl --silent --fail -u "${creds_short}" -X PUT "${destination_path}" -T "${source_path}/meta"
+[[ $? -eq 0  ]] || err "failed to push meta data"
+
+log "image built and pushed to artifactory with meta data"
 log "clean up build path '${build_path}'"
 (rm -rf ${build_path})
 
